package motobeans.architecture.constants

enum class ConstantsApi {
    CALL_TEMP, CALL_SYNC_LOCAL_TO_SERVER, CALL_SYNC_SERVER_TO_LOCAL, CALL_LOGIN,
    CALL_ADD_TASK, CALL_ADD_LEAD, CALL_ALL_MASTER_VALUE, CALL_LOAN_INFO_GET,CALL_LOAN_INFO_POST,
    CALL_SOURCE_CHANNEL_PARTNER_NAME, CALL_LOAN_PRODUCT, CALL_UPDATE_REFERENCE, CALL_PIN_CODE_DETAIL,
    CALL_POST_EMPLOYMENT,CALL_GET_EMPLOYMENT, CALL_DOCUMENT_UPLOAD, CALL_BANK_DETAIL_POST,CALL_BANK_DETAIL_GET,
    CALL_GET_ALL_LEADS, CALL_POST_PERSONAL_INFO, CALL_GET_PERSONAL_INFO, CALL_ALL_STATES,
    CALL_POST_LOAN_APP,CALL_GET_LOAN_APP,
}