package motobeans.architecture.constants

enum class ConstantsApi {
    CALL_TEMP, CALL_SYNC_LOCAL_TO_SERVER, CALL_SYNC_SERVER_TO_LOCAL, CALL_LOGIN, CALL_ALL_STATES,
    CALL_ADD_TASK, CALL_ADD_LEAD, CALL_ALL_MASTER_VALUE, CALL_GET_LOAN_APP, CALL_POST_LOAN_APP,
    CALL_SOURCE_CHANNEL_PARTNER_NAME, CALL_LOAN_PRODUCT, CALL_PIN_CODE_DETAIL,
    CALL_DOCUMENT_UPLOAD, CALL_GET_ALL_LEADS, CALL_PROPERTY_NATURE, CALL_COAPPLICANTS_LIST
}