package motobeans.architecture.constants

enum class ConstantsApi {
    CALL_TEMP, CALL_SYNC_LOCAL_TO_SERVER, CALL_SYNC_SERVER_TO_LOCAL, CALL_LOGIN, CALL_ALL_STATES,
    CALL_ADD_TASK, CALL_ADD_LEAD, CALL_ALL_MASTER_VALUE, CALL_GET_LOAN_APP, CALL_POST_LOAN_APP,
    CALL_SOURCE_CHANNEL_PARTNER_NAME, CALL_LOAN_PRODUCT, CALL_PIN_CODE_DETAIL,
    CALL_DOCUMENT_UPLOAD, CALL_GET_ALL_LEADS, CALL_TRANSACTON_CATEGORY, CALL_COAPPLICANTS_LIST,
    CALL_SEND_OTP, CALL_VERIFY_OTP, CALL_FINAL_SUBMIT, CALL_SYNC_LEAD_LOCAL_TO_SERVER, CALL_SYNC_LEAD_SERVER_TO_LOCAL,
    CALL_UPDATE_CALL, CALL_KYC,CALL_DOC_TYPE,CALL_UPLOADED_DOC
}